name: Test Event

on: 
  push:
    branches: 'main'
  registry_package:
  workflow_dispatch:
  
jobs:
        
  print_context:
    runs-on: ubuntu-latest
    env:
      EVENT_CONTEXT: ${{ toJSON(github.event) }}
    steps:
      - name: Echo event name
        run: echo $GITHUB_EVENT_NAME
      - name: Print event properties
        run: |
          echo $EVENT_CONTEXT
