name: Test Registry Package Event

on:
  [registry_package, workflow_dispatch]
  
jobs:
        
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
